version: '2'
services:
    db:
        container_name: ticket_db
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '3361:3306'
        restart: always
        volumes:
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#            - ./data/db:/var/lib/mysql
            # - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini+

        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ticket
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev2022
            # XDEBUG_CONFIG: "remote_host=${HOST_IP}"
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
 

    php:
        container_name: ticket_php
        build: php-fpm
        ports:
            - '9007:9000'
        volumes:
            - ./:/var/www:cached
            - ./logs/php:/var/www/var/logs:cached
        links:
            - db
    nginx:
        container_name: ticket_nginx
        build: nginx
        ports:
            - '84:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached